version: '3.3'

networks:
  microsite-net:
    driver: bridge

services:
  web:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - microsite-net
    restart: "on-failure" 
